# Generated by Django 5.1.1 on 2024-10-09 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_remove_order_products_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'ordering': ['created_at'], 'verbose_name': 'Заказ продукта (промежуточное)', 'verbose_name_plural': 'Заказы продуктов (промежуточные)'},
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='App.shippingaddress', verbose_name='Адрес доставки'),
        ),
    ]
